/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: victorcalles (https://sketchfab.com/v3dartist)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/michi-bot-3de2985ed85e478387d2829b690d9523
title: Michi Bot
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { LoopPingPong } from "three";

export default function ModelE({ posicion, animacion, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./assets/michi_bot/scene.gltf"
  );
  const { actions } = useAnimations(animations, group);
  const nome = "Take 001";
  let ts = animacion ? 0.2 : 0;
  useEffect(() => {
    actions[nome].timeScale = ts;
    actions[nome].setLoop(LoopPingPong).play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="9720a92d3b9a4d279bb7067fb9d66a02fbx"
            rotation={[Math.PI / 2, 0, 0]}
            position={posicion}
            scale={5}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Geo">
                  <group name="Body" position={[0, -0.19, 0]}>
                    <group
                      name="Head"
                      position={[0, 0.31, 0.09]}
                      rotation={[0, Math.PI / 9, 0]}
                    >
                      <group name="Head_Prop" position={[0, 0.09, -0.09]}>
                        <mesh
                          name="Head_Prop_mat_michi_0"
                          geometry={nodes.Head_Prop_mat_michi_0.geometry}
                          receiveShadow
                          castShadow
                          material={materials.mat_michi}
                        />
                      </group>
                      <mesh
                        name="Head_mat_michi_0"
                        geometry={nodes.Head_mat_michi_0.geometry}
                        receiveShadow
                        castShadow
                        material={materials.mat_michi}
                      />
                    </group>
                    <group name="AlaSup_Low1" position={[0.63, 0.39, 0]}>
                      <group
                        name="Wing_Up_I_1"
                        position={[-0.63, -0.43, 0]}
                        rotation={[0, 0.44, 0]}
                      >
                        <group name="Wing_Up_I" position={[0.52, 0.3, -0.01]}>
                          <mesh
                            name="Wing_Up_I_mat_michi_0"
                            geometry={nodes.Wing_Up_I_mat_michi_0.geometry}
                            receiveShadow
                            castShadow
                            material={materials.mat_michi}
                          />
                        </group>
                      </group>
                      <group
                        name="Wing_Up_D_1"
                        position={[-0.63, -0.43, 0]}
                        rotation={[0, -0.44, 0]}
                      >
                        <group name="Wing_Up_D" position={[-0.52, 0.3, -0.01]}>
                          <mesh
                            name="Wing_Up_D_mat_michi_0"
                            geometry={nodes.Wing_Up_D_mat_michi_0.geometry}
                            receiveShadow
                            castShadow
                            material={materials.mat_michi}
                          />
                        </group>
                      </group>
                    </group>
                    <group name="Wing" position={[0.67, 0.2, 0]}>
                      <group
                        name="Wing_Down_I_1"
                        position={[-0.67, -0.24, 0]}
                        rotation={[0, 0.44, 0]}
                      >
                        <group name="Wing_Down_I" position={[0.59, 0.2, -0.01]}>
                          <mesh
                            name="Wing_Down_I_mat_michi_0"
                            geometry={nodes.Wing_Down_I_mat_michi_0.geometry}
                            receiveShadow
                            castShadow
                            material={materials.mat_michi}
                          />
                        </group>
                      </group>
                      <group
                        name="Wing_Down_D_1"
                        position={[-0.67, -0.24, 0]}
                        rotation={[0, -0.44, 0]}
                      >
                        <group
                          name="Wing_Down_D"
                          position={[-0.59, 0.2, -0.01]}
                          rotation={[-0.12, -0.59, -0.07]}
                        >
                          <mesh
                            name="Wing_Down_D_mat_michi_0"
                            geometry={nodes.Wing_Down_D_mat_michi_0.geometry}
                            receiveShadow
                            castShadow
                            material={materials.mat_michi}
                          />
                        </group>
                      </group>
                    </group>
                    <group name="Shoulder" position={[0, 0.39, 0]}>
                      <group
                        name="Shoulder_I"
                        position={[0.39, -0.31, 0.06]}
                        rotation={[-0.86, 0, 0]}
                      >
                        <group
                          name="Cannon_I"
                          position={[0.06, 0, 0.05]}
                          rotation={[-0.01, 0.13, 0.15]}
                        >
                          <mesh
                            name="Cannon_I_mat_michi_0"
                            geometry={nodes.Cannon_I_mat_michi_0.geometry}
                            receiveShadow
                            castShadow
                            material={materials.mat_michi}
                          />
                        </group>
                        <mesh
                          name="Shoulder_I_mat_michi_0"
                          geometry={nodes.Shoulder_I_mat_michi_0.geometry}
                          receiveShadow
                          castShadow
                          material={materials.mat_michi}
                        />
                      </group>
                      <group
                        name="Shoulder_D"
                        position={[-0.39, -0.31, 0.06]}
                        rotation={[-0.67, 0.28, 0.13]}
                      >
                        <group name="Cannon_D" position={[0.39, 0.31, -0.06]}>
                          <mesh
                            name="Cannon_D_mat_michi_0"
                            geometry={nodes.Cannon_D_mat_michi_0.geometry}
                            receiveShadow
                            castShadow
                            material={materials.mat_michi}
                          />
                        </group>
                        <mesh
                          name="Shoulder_D_mat_michi_0"
                          geometry={nodes.Shoulder_D_mat_michi_0.geometry}
                          receiveShadow
                          castShadow
                          material={materials.mat_michi}
                        />
                      </group>
                    </group>
                    <group name="Cannon" position={[0, 0.39, 0]} />
                    <mesh
                      name="Body_mat_michi_0"
                      geometry={nodes.Body_mat_michi_0.geometry}
                      receiveShadow
                      castShadow
                      material={materials.mat_michi}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./assets/michi_bot/scene.gltf");
