/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Claudia Luehl (https://sketchfab.com/clodbc)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/junkrat-7deb2dd552df4bf4bb65005018176647
title: Junkrat
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function ModelC({ posicion, animacion, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./assets/junkrat/scene.gltf"
  );
  const { actions } = useAnimations(animations, group);
  const nome = "Take 001";
  let ts = animacion ? 0.2 : 0;
  useEffect(() => {
    actions[nome].timeScale = ts;
    actions[nome].play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          castShadow
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.04}
          position={posicion}
        >
          <group
            name="81a39b0745054f9bb436371b8536adedfbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <group
                    name="Bein_Spirale_low"
                    position={[-64.11, 89.28, -23.97]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <primitive object={nodes._rootJoint} />
                  <group
                    name="Object_6"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_8"
                    position={[-148.65, 523.02, -76.18]}
                    rotation={[2.64, 0.09, -0.08]}
                    scale={[0.22, 0.22, 0.25]}
                  />
                  <group
                    name="Object_10"
                    position={[-163.56, 554.63, -60.85]}
                    rotation={[-1.86, -0.52, 0.08]}
                    scale={[0.22, 0.22, 0.25]}
                  />
                  <group
                    name="Object_12"
                    position={[63.95, 598.71, 32.98]}
                    rotation={[-0.49, 0.12, -3.09]}
                    scale={0.58}
                  />
                  <group
                    name="Object_14"
                    position={[64.92, 621.8, 7.43]}
                    rotation={[-1.25, 0.17, -3.1]}
                    scale={0.58}
                  />
                  <group
                    name="Object_16"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_18"
                    position={[-52.09, 598.73, 29.19]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_20"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_22"
                    position={[-145.75, 546.87, -74.74]}
                    rotation={[-2.56, 0.26, -0.31]}
                    scale={[0.22, 0.22, 0.25]}
                  />
                  <group
                    name="Object_24"
                    position={[70.98, 637.07, -24.96]}
                    rotation={[-1.57, 0.28, -3.13]}
                    scale={0.58}
                  />
                  <group
                    name="Object_26"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_28"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_30"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_32"
                    position={[0, 524.53, -74.36]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_34"
                    position={[41.45, 565.08, 48.92]}
                    rotation={[1.35, 0.01, -0.48]}
                    scale={0.58}
                  />
                  <group
                    name="Object_36"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_40"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_42"
                    position={[0, 690.65, 27.95]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_44"
                    position={[-41.19, 416.21, 62.58]}
                    rotation={[-Math.PI / 2, 0.23, -0.42]}
                    scale={0.71}
                  />
                  <group
                    name="Object_46"
                    position={[-273.71, 441.47, 8.02]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_48"
                    position={[0, 503.18, -48.9]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_50"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_52"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_54"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_56"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_58"
                    position={[-260.24, 445.08, 43.32]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_60"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_62"
                    position={[-232.14, 482.65, 4.6]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_64"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_66"
                    position={[-154.16, 533.88, -60.59]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_68"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_70"
                    position={[-262.83, 459, 41.95]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_72"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_74"
                    position={[-58.46, 150.5, -9.26]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Object_76"
                    position={[-64.24, 87.88, -24.32]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Object_78"
                    position={[-61.17, 118.38, -16.59]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Object_80"
                    position={[-59.34, 139.28, -11.99]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Object_82"
                    position={[-57.56, 158.06, 29.49]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Object_84"
                    position={[-54.93, 187.27, 6.91]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Object_86"
                    position={[-66.5, 60.24, -30.5]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Object_88"
                    position={[-58.78, 145.83, 15.31]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Object_90"
                    position={[-66.16, 64.84, -29.38]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Object_92"
                    position={[-51.74, 222.34, 0.77]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Object_94"
                    position={[-53.09, 206.82, 42.16]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Object_96"
                    position={[-58.78, 145.83, 15.31]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Object_98"
                    position={[-49.39, 248.19, -0.58]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Object_100"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Object_102"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Object_104"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Object_106"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Object_108"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Object_110"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Object_112"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Object_114"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Object_116"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Object_118"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Object_120"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Object_122"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Object_124"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Object_126"
                    position={[0, 690.65, 27.95]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_128"
                    position={[0, 690.65, 28.24]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Base_Human003"
                    position={[0.51, 0, -3.55]}
                    rotation={[Math.PI / 2, Math.PI / 2, 0]}
                  />
                  <group
                    name="K��rper_Riemen_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Cylinder003"
                    position={[-148.65, 523.02, -76.18]}
                    rotation={[2.64, 0.09, -0.08]}
                    scale={[0.22, 0.22, 0.25]}
                  />
                  <group
                    name="Cylinder001"
                    position={[-163.56, 554.63, -60.85]}
                    rotation={[-1.86, -0.52, 0.08]}
                    scale={[0.22, 0.22, 0.25]}
                  />
                  <group
                    name="Granate_low001"
                    position={[52.91, 596.56, 29.98]}
                    rotation={[-0.49, 0.12, -3.09]}
                    scale={0.58}
                  />
                  <group
                    name="Granate_low002"
                    position={[53.71, 618.7, 6.84]}
                    rotation={[-1.25, 0.17, -3.1]}
                    scale={0.58}
                  />
                  <group
                    name="Hand_Unten_Grundk��rper_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Granate_low006"
                    position={[-52.09, 598.73, 29.19]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="R��ckenhalterung_Rad_oben_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Cylinder002"
                    position={[-145.75, 546.87, -74.74]}
                    rotation={[-2.56, 0.26, -0.31]}
                    scale={[0.22, 0.22, 0.25]}
                  />
                  <group
                    name="Granate_low003"
                    position={[59.5, 635.14, -24.8]}
                    rotation={[-1.57, 0.28, -3.13]}
                    scale={0.58}
                  />
                  <group
                    name="Tasche_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Schuh_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="R��ckenhalterung_unten_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="R��ckenhalterung_Zylinder_low"
                    position={[0, 524.53, -74.36]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Granate_low"
                    position={[50.72, 569, 43.06]}
                    rotation={[1.35, 0.01, -0.48]}
                    scale={0.58}
                  />
                  <group
                    name="K��rper_Fleisch_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="K��rper_Stoff_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Augen_low"
                    position={[0, 690.65, 27.95]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Wasserflasche_low"
                    position={[-41.19, 416.21, 62.58]}
                    rotation={[-Math.PI / 2, 0.23, -0.42]}
                    scale={0.71}
                  />
                  <group
                    name="Hand_runde_platte_low"
                    position={[-273.71, 441.47, 8.02]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="R��ckenhalterung_Ring_unten_low"
                    position={[0, 503.18, -48.9]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Hand_Obenteil_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Armring_rechts_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Verband_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="K��rper_Handschuh_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Hand_4eck_unten_low"
                    position={[-260.24, 445.08, 43.32]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Hand_Finger_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Hand_Kugel_low"
                    position={[-232.14, 482.65, 4.6]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Hose_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Ellebogenpanzer_low"
                    position={[-154.16, 533.88, -60.59]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="K��rper_R��ckendinger_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Hand_4eck_oben_low"
                    position={[-262.83, 459, 41.95]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Haare_low"
                    position={[0, 283.49, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Bein_Rolle_unten_low"
                    position={[-58.46, 150.5, -9.26]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Bein_Spirale_Ende_oben_low"
                    position={[-61.17, 118.38, -16.59]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Bein_Verbindung_unten_low"
                    position={[-59.34, 139.28, -11.99]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Bein_gro��e_Platte_unten_low"
                    position={[-57.56, 158.06, 29.49]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Bein_Rolle_oben_low"
                    position={[-54.93, 187.27, 6.91]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Bein_Spirale_Ende_unten_low"
                    position={[-66.5, 60.24, -30.5]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Bein_B��gel_gro��_low"
                    position={[-58.78, 145.83, 15.31]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Bein_Beinstab_low"
                    position={[-66.16, 64.84, -29.38]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Bein_Kasten_low"
                    position={[-51.74, 222.34, 0.77]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Bein_gro��e_Platte_oben_low"
                    position={[-53.09, 206.82, 42.16]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Bein_B��gel_klein_low"
                    position={[-58.78, 145.83, 15.31]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Bein_Verbindung_oben_low"
                    position={[-49.39, 248.19, -0.58]}
                    rotation={[-1.33, 0.09, -0.02]}
                    scale={[1.18, 1.11, 1.07]}
                  />
                  <group
                    name="Rad_Gummiding_low"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Rad_Stachel_3_low"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Rad_Kettenglieder_low"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Rad_Rad1_low"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Rad_Schrauben_low"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Rad_Stachel_2_low"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Rad_Stachel_4_low"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Rad_Platte_low"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Rad_Deckel_gelb_low"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Rad_Rad2_low"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Rad_rand_l��cher_low"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Rad_Rand_silber_low"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Rad_Stachel_1_low"
                    position={[0.38, 557.55, -137.68]}
                    rotation={[Math.PI, 0, 0]}
                    scale={1.14}
                  />
                  <group
                    name="Augelow2"
                    position={[0, 690.65, 27.95]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Augen_low001"
                    position={[0, 690.65, 28.24]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    name="Object_15"
                    geometry={nodes.Object_15.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_15.skeleton}
                  />
                  <skinnedMesh
                    name="Object_17"
                    geometry={nodes.Object_17.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_17.skeleton}
                  />
                  <skinnedMesh
                    name="Object_19"
                    geometry={nodes.Object_19.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <skinnedMesh
                    name="Object_21"
                    geometry={nodes.Object_21.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_21.skeleton}
                  />
                  <skinnedMesh
                    name="Object_23"
                    geometry={nodes.Object_23.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_23.skeleton}
                  />
                  <skinnedMesh
                    name="Object_25"
                    geometry={nodes.Object_25.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_25.skeleton}
                  />
                  <skinnedMesh
                    name="Object_27"
                    geometry={nodes.Object_27.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_27.skeleton}
                  />
                  <skinnedMesh
                    name="Object_29"
                    geometry={nodes.Object_29.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_29.skeleton}
                  />
                  <skinnedMesh
                    name="Object_31"
                    geometry={nodes.Object_31.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_31.skeleton}
                  />
                  <skinnedMesh
                    name="Object_33"
                    geometry={nodes.Object_33.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_33.skeleton}
                  />
                  <skinnedMesh
                    name="Object_35"
                    geometry={nodes.Object_35.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_35.skeleton}
                  />
                  <skinnedMesh
                    name="Object_37"
                    geometry={nodes.Object_37.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_34}
                    skeleton={nodes.Object_37.skeleton}
                  />
                  <skinnedMesh
                    name="Object_38"
                    geometry={nodes.Object_38.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_38.skeleton}
                  />
                  <skinnedMesh
                    name="Object_39"
                    geometry={nodes.Object_39.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_39.skeleton}
                  />
                  <skinnedMesh
                    name="Object_41"
                    geometry={nodes.Object_41.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_41.skeleton}
                  />
                  <skinnedMesh
                    name="Object_43"
                    geometry={nodes.Object_43.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_34}
                    skeleton={nodes.Object_43.skeleton}
                  />
                  <skinnedMesh
                    name="Object_45"
                    geometry={nodes.Object_45.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_45.skeleton}
                  />
                  <skinnedMesh
                    name="Object_47"
                    geometry={nodes.Object_47.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_47.skeleton}
                  />
                  <skinnedMesh
                    name="Object_49"
                    geometry={nodes.Object_49.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_49.skeleton}
                  />
                  <skinnedMesh
                    name="Object_51"
                    geometry={nodes.Object_51.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_51.skeleton}
                  />
                  <skinnedMesh
                    name="Object_53"
                    geometry={nodes.Object_53.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_53.skeleton}
                  />
                  <skinnedMesh
                    name="Object_55"
                    geometry={nodes.Object_55.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_55.skeleton}
                  />
                  <skinnedMesh
                    name="Object_57"
                    geometry={nodes.Object_57.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_57.skeleton}
                  />
                  <skinnedMesh
                    name="Object_59"
                    geometry={nodes.Object_59.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_59.skeleton}
                  />
                  <skinnedMesh
                    name="Object_61"
                    geometry={nodes.Object_61.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_61.skeleton}
                  />
                  <skinnedMesh
                    name="Object_63"
                    geometry={nodes.Object_63.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_63.skeleton}
                  />
                  <skinnedMesh
                    name="Object_65"
                    geometry={nodes.Object_65.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_65.skeleton}
                  />
                  <skinnedMesh
                    name="Object_67"
                    geometry={nodes.Object_67.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_67.skeleton}
                  />
                  <skinnedMesh
                    name="Object_69"
                    geometry={nodes.Object_69.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_69.skeleton}
                  />
                  <skinnedMesh
                    name="Object_71"
                    geometry={nodes.Object_71.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_22}
                    skeleton={nodes.Object_71.skeleton}
                  />
                  <skinnedMesh
                    name="Object_73"
                    geometry={nodes.Object_73.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_34}
                    skeleton={nodes.Object_73.skeleton}
                  />
                  <skinnedMesh
                    name="Object_75"
                    geometry={nodes.Object_75.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_75.skeleton}
                  />
                  <skinnedMesh
                    name="Object_77"
                    geometry={nodes.Object_77.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_77.skeleton}
                  />
                  <skinnedMesh
                    name="Object_79"
                    geometry={nodes.Object_79.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_79.skeleton}
                  />
                  <skinnedMesh
                    name="Object_81"
                    geometry={nodes.Object_81.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_81.skeleton}
                  />
                  <skinnedMesh
                    name="Object_83"
                    geometry={nodes.Object_83.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_83.skeleton}
                  />
                  <skinnedMesh
                    name="Object_85"
                    geometry={nodes.Object_85.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_85.skeleton}
                  />
                  <skinnedMesh
                    name="Object_87"
                    geometry={nodes.Object_87.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_87.skeleton}
                  />
                  <skinnedMesh
                    name="Object_89"
                    geometry={nodes.Object_89.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_89.skeleton}
                  />
                  <skinnedMesh
                    name="Object_91"
                    geometry={nodes.Object_91.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_91.skeleton}
                  />
                  <skinnedMesh
                    name="Object_93"
                    geometry={nodes.Object_93.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_93.skeleton}
                  />
                  <skinnedMesh
                    name="Object_95"
                    geometry={nodes.Object_95.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_95.skeleton}
                  />
                  <skinnedMesh
                    name="Object_97"
                    geometry={nodes.Object_97.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_97.skeleton}
                  />
                  <skinnedMesh
                    name="Object_99"
                    geometry={nodes.Object_99.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_19}
                    skeleton={nodes.Object_99.skeleton}
                  />
                  <skinnedMesh
                    name="Object_101"
                    geometry={nodes.Object_101.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_20}
                    skeleton={nodes.Object_101.skeleton}
                  />
                  <skinnedMesh
                    name="Object_103"
                    geometry={nodes.Object_103.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_20}
                    skeleton={nodes.Object_103.skeleton}
                  />
                  <skinnedMesh
                    name="Object_105"
                    geometry={nodes.Object_105.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_20}
                    skeleton={nodes.Object_105.skeleton}
                  />
                  <skinnedMesh
                    name="Object_107"
                    geometry={nodes.Object_107.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_20}
                    skeleton={nodes.Object_107.skeleton}
                  />
                  <skinnedMesh
                    name="Object_109"
                    geometry={nodes.Object_109.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_20}
                    skeleton={nodes.Object_109.skeleton}
                  />
                  <skinnedMesh
                    name="Object_111"
                    geometry={nodes.Object_111.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_20}
                    skeleton={nodes.Object_111.skeleton}
                  />
                  <skinnedMesh
                    name="Object_113"
                    geometry={nodes.Object_113.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_20}
                    skeleton={nodes.Object_113.skeleton}
                  />
                  <skinnedMesh
                    name="Object_115"
                    geometry={nodes.Object_115.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_20}
                    skeleton={nodes.Object_115.skeleton}
                  />
                  <skinnedMesh
                    name="Object_117"
                    geometry={nodes.Object_117.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_20}
                    skeleton={nodes.Object_117.skeleton}
                  />
                  <skinnedMesh
                    name="Object_119"
                    geometry={nodes.Object_119.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_20}
                    skeleton={nodes.Object_119.skeleton}
                  />
                  <skinnedMesh
                    name="Object_121"
                    geometry={nodes.Object_121.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_20}
                    skeleton={nodes.Object_121.skeleton}
                  />
                  <skinnedMesh
                    name="Object_123"
                    geometry={nodes.Object_123.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_20}
                    skeleton={nodes.Object_123.skeleton}
                  />
                  <skinnedMesh
                    name="Object_125"
                    geometry={nodes.Object_125.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_20}
                    skeleton={nodes.Object_125.skeleton}
                  />
                  <skinnedMesh
                    name="Object_127"
                    geometry={nodes.Object_127.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_34}
                    skeleton={nodes.Object_127.skeleton}
                  />
                  <skinnedMesh
                    name="Object_129"
                    geometry={nodes.Object_129.geometry}
                    receiveShadow
                    castShadow
                    material={materials.Material_34}
                    skeleton={nodes.Object_129.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/junkrat/scene.gltf");
